// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Audit
{
    public long Id { get; set; }

    public Guid EntityId { get; set; }

    public string EntityType { get; set; }

    public string Event { get; set; }

    public string Data { get; set; }

    public DateTime Timestamp { get; set; }

    public string By { get; set; }
}