// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Brand
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public Guid CompanyId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<Performer> Performer { get; } = new List<Performer>();
}