// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Company
{
    public Guid Id { get; set; }

    public Guid BrandId { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }
}