// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Company
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Description { get; set; }

    public Guid UserId { get; set; }

    public virtual ICollection<Brand> Brand { get; } = new List<Brand>();

    public virtual User User { get; set; }
}