// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Performer
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid BrandId { get; set; }

    public short WorkingHourStart { get; set; }

    public short WorkingHourEnd { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<Reservation> Reservation { get; } = new List<Reservation>();
}