// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BookingApi.Data.Models;

public partial class Reservation
{
    public Guid Id { get; set; }

    public string UserEmailAddress { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }
}